# Base packages installed on all systems
# These packages are included regardless of host or modules

description: Base system packages

packages:
  # Essential base system
  - linux-zen
  - linux-zen-headers
  - base
  - base-devel
  - tree
  - git
  - github-cli
  - lazygit
  - vim
  - neovim
  - flatpak
  - icon-browser-git
  - dkms
  # apps
  - localsend
  # - telegram-desktop # bad signature in cachy repo
  - 7zip
  - feh
  - network-manager-applet
  - blueman
  - gnome-disk-utility
  - lact
  - satty
  - diskonaut
  - zen-browser-bin
  - brave-bin
  - alacritty
  - gnome-software
  - flatpak:com.github.tchx84.Flatseal
  - flatpak:io.missioncenter.MissionCenter
  - flatpak:com.protonvpn.www
